blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from blog.models import Artikel
from .views import(
    BlogList,
    BlogDetail,
    BlogCategory,
    BlogCreate,
    BlogManage,
    BlogDelete,
    BlogUpdate,
    BlogSearch,
)

from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
    path('search/', BlogSearch.as_view(), name='search'),
    re_path(r'^manage/update/(?P<pk>\d+)$',
            BlogUpdate.as_view(), name='update'),
    re_path(r'^manage/delete/(?P<pk>\d+)$',
            BlogDelete.as_view(), name='delete'),
    path('manage/', BlogManage.as_view(), name='manage'),
    path('tambah/', BlogCreate.as_view(), name='create'),
    re_path(r'^kategori/(?P<slug>[\w-]+)/(?P<page>\d+)$',
            BlogCategory.as_view(), name='category'),
    re_path(r'^detail/(?P<slug>[\w-]+)$', BlogDetail.as_view(), name='detail'),
    re_path(r'^(?P<page>\d+)$', BlogList.as_view(), name='list'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from .views import Home
from blog.models import Artikel

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('account/', include('account.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    re_path(r'^$', Home.as_view(), name='home'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/banner.html
{% load static %}
<header>
    <div class="jumbotron jumbotron-fluid background-banner">
        <div class="container-fluid mt-6">
            <div class="row m-auto banner">

                <div class="col-md-6 mt-5 gambar-banner">
                    <img src="{% static 'img/arduino.png' %}">
                </div>
                <div class="col-md-6 mt-5 tulisan-banner">
                    <h1>My Banner</h1>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Expedita, animi. Quos unde molestiae omnis optio! Esse,
                        illum a. Voluptatem earum magni, at aspernatur nisi consectetur
                        quisquam reiciendis est doloribus quia!</p>
                    <a href="#" type="button" class="btn btn-outline-primary">Read More</a>
                </div>
            </div>
        </div>
    </div>
</header>

templates/snippets/blog_list.html
{% load static %}
<section class="mt-2">
    <!-- Search -->
    {% include 'snippets/search.html' %}
</section>

<section>
    <div class="container text-center">
        <hr>
        <h2>Recent Post</h2>
        <hr>
    </div>
    <div class="blog-area">
        <div class="container">
            <div class="row">
                {% for artikel in last_artikel %}
                <div class="col-12 col-sm-6 col-lg-4">
                    <div class="shadow">
                        <div class="single-post-area">
                            <!-- Post Thumbnail -->
                            <a href="{% url 'blog:detail' artikel.slug %}" class="post-thumbnail"><img
                                    src="{{artikel.thumbnail.url}}" alt=""></a>
                            <!-- Post Catagory -->
                            <a href="{% url 'blog:category' artikel.kategori.slug 1 %}"
                                class="btn post-catagory">{{artikel.kategori}}</a>
                        </div>
                        <div class="post-content-wrap">
                            <div class="container post-content-sm">
                                <div class="post-meta">
                                    <p>{{artikel.isi|truncatewords:20|safe}}</p>
                                    <a href="#">{{artikel.published}}</a>
                                </div>
                                <a href="{% url 'blog:detail' artikel.slug %}" class="post-title">{{artikel.judul}}</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container text-center">
        <hr>
        <h2>Category</h2>
        <hr>
    </div>
    <div class="container w-50 m-auto">
        <div class="row">
            <div class="col-12 text-center">
                {% for artikel in last_artikel %}
                <a href="{% url 'blog:category' artikel.kategori.slug 1 %}"
                    class="btn btn-outline-dark btn-category m-2">
                    {{artikel.kategori|upper}} </a>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

templates/snippets/navbar.html
<nav class="navbar navbar-expand-md navbar-light shadow-sm">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler"
        aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="awal navbar-brand" href="{% url 'home'%}">FunTech</a>
    <div class="collapse navbar-collapse" id="navbarToggler">
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home'%}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:list' 1 %}">Blog</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Project</a>
            </li>
            <a class="navbar-brand" href="{% url 'home'%}">FunTech</a>
            <li class="nav-item">
                <a class="nav-link" href="#">Portfolio</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">About</a>
            </li>

            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                    aria-expanded="false">Manage</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
                    <a class="dropdown-item" href="{% url 'blog:create' %}">Add Post</a>
                    <a class="dropdown-item" href="{% url 'blog:manage' %}">Post List</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                    aria-expanded="false">User</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                    <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                </div>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/snippets/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'vendor/jquery/jquery-3.4.1.slim.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/font-awesome/all.min.js' %}"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script> -->
<script src="{% static 'vendor/OwlCarousel/owl.carousel.min.js' %}"></script>

templates/snippets/search.html
{% load static %}
<div class="container">
    <form class="form-check-inline" action="{% url 'blog:search' %}">
        <input class="form-control" type="text" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-light btn-rounded" type="submit"><span><i class="fas fa-search"></i></span></button>
    </form>
</div>

templates/snippets/social_media.html
<section>
    <div class="container text-center">
        <hr>
        <h4>Our Contact</h4>
        <hr>
    </div>

    <div class="container-fluid mt-3">
        <div class="row text-center">
            <div class="col-12 social">
                <a href="#"><i class="fab fa-facebook"></i></a>
                <a href="#"><i class="fab fa-github-alt"></i></a>
                <a href="#"><i class="fab fa-google-plus-g"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
                <a href="#"><i class="fab fa-youtube"></i></a>
            </div>
        </div>
    </div>
</section>

templates/snippets/styles.html
{% load static %}



<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<!-- <link rel="stylesheet" href="{% static 'css/search.css' %}"> -->
<!-- <link rel="stylesheet" href="{% static 'css/main_login.css' %}"> -->
<!-- <link rel="stylesheet" href="{% static 'css/blog.css' %}"> -->
<link rel="stylesheet" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/OwlCarousel/assets/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/OwlCarousel/assets/owl.theme.default.min.css' %}">

templates/snippets/three_box.html
{% load static %}
<section>
    <div class="d-md-flex flex-row justify-content-md-around box">
        <div class="p-3">
            <div class="container bg-light text-center p-3 shadow">
                <h5 class="box-title">Blog</h5>
                <hr class="my-4">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                <a href="{% url 'blog:list' 1 %}" type="button" class="btn btn-danger">Read Blog</a>
            </div>
        </div>
        <div class="p-3">
            <div class="container bg-light text-center p-3 shadow">
                <h5 class="box-title">Project</h5>
                <hr class="my-4">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                <a href="#" type="button" class="btn btn-primary">Open Project</a>
            </div>
        </div>
        <div class="p-3">
            <div class="container bg-light text-center p-3 shadow">
                <h5 class="box-title">About</h5>
                <hr class="my-4">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                <a href="#" type="button" class="btn btn-danger">Read About</a>
            </div>
        </div>
    </div>
</section>