blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from blog.models import Artikel
from .views import(
    BlogList,
    BlogDetail,
    BlogCategory,
    BlogCreate,
    BlogManage,
    BlogDelete,
    BlogUpdate,
    BlogSearch,
)

from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
    path('search/', BlogSearch.as_view(), name='search'),
    re_path(r'^manage/update/(?P<pk>\d+)$',
            BlogUpdate.as_view(), name='update'),
    re_path(r'^manage/delete/(?P<pk>\d+)$',
            BlogDelete.as_view(), name='delete'),
    path('manage/', BlogManage.as_view(), name='manage'),
    path('tambah/', BlogCreate.as_view(), name='create'),
    re_path(r'^kategori/(?P<slug>[\w-]+)/(?P<page>\d+)$',
            BlogCategory.as_view(), name='category'),
    re_path(r'^detail/(?P<slug>[\w-]+)$', BlogDetail.as_view(), name='detail'),
    re_path(r'^(?P<page>\d+)$', BlogList.as_view(), name='list'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from .views import Home
from blog.models import Artikel

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('account/', include('account.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    re_path(r'^$', Home.as_view(), name='home'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from PIL import Image
from django.utils import timezone
from django.contrib.auth.models import User

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class Category(models.Model):
    name = models.CharField(max_length=15)
    slug = models.SlugField(blank=True, editable=False)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return f"{self.name}"

    def save(self):
        self.slug = slugify(self.name)
        super().save()


class Artikel(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    judul = models.CharField(max_length=255)
    thumbnail = models.ImageField(
        blank=True, null=True, upload_to="images/", default='images/default.jpg')
    isi = RichTextUploadingField(blank=True, null=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='artikel')
    kategori = models.ForeignKey(Category,
                                 on_delete=models.CASCADE,
                                 related_name='artikel')
    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(blank=True, editable=False)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')

    class Meta:
        ordering = ('-published',)

    def save(self):
        self.slug = slugify(self.judul)
        super().save()

        img = Image.open(self.thumbnail.path)

        if img.height > 390 and img.width > 580:
            output_size = (580, 390)
            img.thumbnail(output_size)
            img.save(self.thumbnail.path)

    def get_absolute_url(self):
        url_slug = {'slug': self.slug}
        return reverse('blog:detail', kwargs=url_slug)

    def __str__(self):
        return f"{self.judul}"

blog/forms.py
from django import forms
from .models import Artikel


class AddForm(forms.ModelForm):
    class Meta:
        model = Artikel
        fields = ['judul', 'thumbnail', 'isi', 'author', 'kategori']

        widgets = {
            'judul': forms.TextInput(attrs={'class': 'form-control'}),
            'thumbnail': forms.FileInput(attrs={'class': 'custom-file'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'kategori': forms.Select(attrs={'class': 'form-control'})
        }


class EditForm(forms.ModelForm):
    class Meta:
        model = Artikel
        fields = ['judul', 'isi', 'kategori']

        widgets = {
            'judul': forms.TextInput(attrs={'class': 'form-control'}),
            'kategori': forms.TextInput(attrs={'class': 'form-control'})
        }

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.db.models import Q
from django.views.generic import(
    DetailView,
    DeleteView,
    UpdateView,
    CreateView,
    ListView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
from .models import Artikel, Category
from .forms import AddForm, EditForm


class BlogSearch(ListView):
    def get(self, request, *args, **kwargs):
        queryset = Artikel.objects.all()
        query = request.GET.get('q')
        # print(query)
        if query:
            queryset = queryset.filter(Q(judul__icontains=query)).distinct()

        context = {
            'artikels': queryset,
        }
        return render(request, 'blog/blog_search.html', context)


class BlogUpdate(LoginRequiredMixin, UpdateView):
    model = Artikel
    form_class = EditForm
    template_name = "blog/blog_update.html"


class BlogDelete(LoginRequiredMixin, DeleteView):
    model = Artikel
    template_name = "blog/blog_delete.html"
    success_url = reverse_lazy('blog:manage')


class BlogManage(LoginRequiredMixin, ListView):
    model = Artikel
    template_name = "blog/blog_manage.html"
    context_object_name = 'artikels'

    def get_context_data(self, *args, **kwargs):
        artikel = self.model.objects.filter(author=self.request.user)
        self.kwargs.update({'artikels': artikel})
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)


class BlogCreate(LoginRequiredMixin, CreateView):
    form_class = AddForm
    template_name = "blog/blog_create.html"


class BlogCategory(ListView):
    model = Artikel
    # category = Category
    template_name = "blog/blog_kategori.html"
    context_object_name = 'artikels'
    ordering = ['-published']
    paginate_by = 3

    def get_queryset(self):
        self.queryset = self.model.objects.filter(
            kategori__slug=self.kwargs['slug'])
        return super().get_queryset()

    def get_context_data(self, *args, **kwargs):
        kategori_list = self.model.objects.order_by(
            'kategori').distinct('kategori').values_list(
                'kategori__slug', flat=True).exclude(
                    kategori__slug=self.kwargs['slug'])

        self.kwargs.update({'kategori_list': kategori_list})
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)


class BlogDetail(DetailView):
    model = Artikel
    template_name = "blog/blog_detail.html"
    context_object_name = 'artikels'


class BlogList(ListView):
    model = Artikel
    template_name = "blog/blog_list.html"
    context_object_name = 'artikels'
    ordering = ['-published']
    paginate_by = 3

    def get_context_data(self, *args, **kwargs):
        kategori_list = self.model.objects.values_list(
            'kategori__slug', flat=True).distinct()

        # print(set(kategori_list))
        self.kwargs.update({'kategori_list': set(kategori_list)})
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)


class LastUpdateArtikel():
    model = Artikel

    def latest_artikel(self):
        last_artikel = self.model.objects.values_list(
            'kategori__name', flat=True).order_by('kategori__name').distinct('kategori__name')

        queryset = []
        for artikels in last_artikel:
            artikel = self.model.objects.filter(
                kategori__name=artikels).latest('published')
            queryset.append(artikel)

        return queryset

templates/blog/blog_create.html
{% extends 'base.html' %}
{% load static %}

{% block style %}

{% endblock style %}


{% block content %}
<div class="container text-center mt-5">
    <h1>Create Artikel</h1>
</div>
<div class="container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form.as_p}}
        <br>
        <button type="submit" class="btn btn-primary w-100">Tambah</button>
    </form>
</div>
{% endblock content %}

templates/blog/blog_delete.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/blog.css' %}">
{% endblock style %}

{% block content %}
<div class="container mt-5">
    <h1>Delete Article</h1>
    <p>Are you sure for delete this article?</p>
</div>
<div class="container mt-3">
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-primary">Ya</button>
        <a href="{% url 'blog:manage' %}" class="btn btn-outline-danger">Tidak</a>
    </form>
</div>
{% endblock content %}

templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/blog.css' %}">
{% endblock style %}


{% block content %}
<div class="container mt-1 pt-3 pb-5 shadow-sm bg-light detail">
    <h1>{{artikels.judul}}</h1>
    <h6 class="mt-2 mb-2">Kategori: {{artikels.kategori}} | {{artikels.published}}</h3>
        {{artikels.isi|safe}}
</div>
{% endblock content %}

templates/blog/blog_kategori.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/blog.css' %}">
{% endblock style %}


{% block content %}
<section class="mt-2">
    <!-- Search -->
    {% include 'snippets/search.html' %}
</section>

<section>
    <div class="container text-center mt-4">
        <hr>

        <h2>{{slug|upper}}</h2>

        <hr>
    </div>

    <div class="blog-area">
        <div class="container">
            <div class="row">
                {% for artikel in artikels %}
                {% if forloop.counter == 1 %}
                <div class="col-12 col-lg-6">
                    <div class="single-post-area">
                        <a href="#" class="post-thumbnail"><img src="{{artikel.thumbnail.url}}" alt=""></a>
                        <a href="{% url 'blog:category' artikel.kategori.slug 1 %}"
                            class="btn post-catagory">{{artikel.kategori}}</a>
                        <div class="post-content">
                            <div class="post-meta">
                                <a href="#">{{artikel.published}}</a>
                            </div>
                            <a href="{% url 'blog:detail' artikel.slug %}" class="post-title">{{artikel.judul}}</a>
                        </div>
                    </div>
                </div>
                {% else %}
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="shadow">
                        <div class="single-post-area">
                            <!-- Post Thumbnail -->
                            <a href="{% url 'blog:detail' artikel.slug %}" class="post-thumbnail"><img
                                    src="{{artikel.thumbnail.url}}" alt=""></a>
                            <!-- Post Catagory -->
                            <a href="{% url 'blog:category' artikel.kategori.slug 1 %}"
                                class="btn post-catagory">{{artikel.kategori}}</a>
                        </div>
                        <div class="post-content-wrap">
                            <!-- Post Conetent -->
                            <div class="container post-content-sm">
                                <div class="post-meta">
                                    {{artikel.isi|truncatewords:12|safe}}
                                    <br>
                                    <a href="#">{{artikel.published}}</a>
                                </div>
                                <a href="{% url 'blog:detail' artikel.slug %}" class="post-title">{{artikel.judul}}</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}

                {% if is_paginated %}
                <div class="col-12">
                    <div class="d-flex justify-content-center w-100">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="{% url 'blog:list' page_obj.previous_page_number %}"
                                        aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                </li>
                                {% endif %}


                                {% for page in paginator.page_range %}
                                <li class="page-item"><a class="page-link"
                                        href="{% url 'blog:list' page %}">{{page}}</a>
                                </li>
                                {% endfor %}

                                {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="{% url 'blog:list' page_obj.next_page_number %}"
                                        aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container text-center">
        <hr>
        <h2>Category</h2>
        <hr>
    </div>


    <div class="container w-50 m-auto">
        <div class="row">
            <div class="col-12 text-center">
                {% for cat in kategori_list %}
                <a href="{% url 'blog:category' cat 1 %}" class="btn btn-outline-dark btn-category m-2">
                    {{cat|upper}} </a>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/blog/blog_list.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/blog.css' %}">
{% endblock style %}


{% block content %}

<section class="mt-2">
    <!-- Search -->
    {% include 'snippets/search.html' %}
</section>

<section>
    <div class="container text-center mt-4">
        <hr>
        <h2>All Posts</h2>
        <hr>
    </div>

    <div class="blog-area">
        <div class="container">
            <div class="row">
                {% for artikel in artikels %}
                {% if forloop.counter == 1 %}
                <div class="col-12 col-lg-6">
                    <div class="single-post-area">
                        <!-- Post Thumbnail -->
                        <a href="#" class="post-thumbnail"><img src="{{artikel.thumbnail.url}}" alt=""></a>
                        <!-- Post Catagory -->
                        <a href="{% url 'blog:category' artikel.kategori.slug 1 %}"
                            class="btn post-catagory">{{artikel.kategori}}</a>
                        <!-- Post Conetent -->
                        <div class="post-content">
                            <div class="post-meta">
                                <a href="#">{{artikel.published}}</a>
                            </div>
                            <a href="{% url 'blog:detail' artikel.slug %}" class="post-title">{{artikel.judul}}</a>
                        </div>
                    </div>
                </div>
                {% else %}
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="shadow">
                        <div class="single-post-area">
                            <!-- Post Thumbnail -->
                            <a href="{% url 'blog:detail' artikel.slug %}" class="post-thumbnail"><img
                                    src="{{artikel.thumbnail.url}}" alt=""></a>
                            <!-- Post Catagory -->
                            <a href="{% url 'blog:category' artikel.kategori.slug 1 %}"
                                class="btn post-catagory">{{artikel.kategori}}</a>
                        </div>
                        <div class="post-content-wrap">
                            <!-- Post Conetent -->
                            <div class="container post-content-sm">
                                <div class="post-meta">
                                    {{artikel.isi|truncatewords:12|safe}}
                                    <br>
                                    <a href="#">{{artikel.published}}</a>
                                </div>
                                <a href="{% url 'blog:detail' artikel.slug %}" class="post-title">{{artikel.judul}}</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}

                {% if is_paginated %}
                <div class="col-12">
                    <div class="d-flex justify-content-center w-100">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="{% url 'blog:list' page_obj.previous_page_number %}"
                                        aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                </li>
                                {% endif %}


                                {% for page in paginator.page_range %}
                                <li class="page-item"><a class="page-link"
                                        href="{% url 'blog:list' page %}">{{page}}</a>
                                </li>
                                {% endfor %}

                                {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="{% url 'blog:list' page_obj.next_page_number %}"
                                        aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>


<section>
    <div class="container text-center">
        <hr>
        <h2>Category</h2>
        <hr>
    </div>

    <div class="container w-50 m-auto">
        <div class="row">
            <div class="col-12 text-center">
                {% for artikel in kategori_list %}
                <a href="{% url 'blog:category' artikel 1 %}" class="btn btn-outline-dark btn-category m-2">
                    {{artikel|upper}} </a>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/blog/blog_manage.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/blog.css' %}">
{% endblock style %}


{% block content %}
<div class="container text-center mt-5">
    <h1>Manage Article</h1>
</div>
<div class="container mt-3 text-center">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Judul</th>
                <th scope="col">Kategori</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for artikel in artikels  %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{artikel.judul}}</td>
                <td>{{artikel.kategori}}</td>
                <td>
                    <a href="{% url 'blog:update' artikel.id %}" class="btn btn-danger">Edit</a>
                    <a href="{% url 'blog:delete' artikel.id %}" class="btn btn-warning">Hapus</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

templates/blog/blog_search.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/blog.css' %}">
{% endblock style %}


{% block content %}
<section class="mt-2">
    <!-- Search -->
    {% include 'snippets/search.html' %}
</section>

<section>
    <div class="container text-center mt-4">
        <hr>
        <h2>Result</h2>
        <hr>
    </div>

    <div class="blog-area">
        <div class="container">
            <div class="row">
                {% for artikel in artikels %}
                {% if forloop.counter == 1 %}
                <div class="col-12 col-lg-6">
                    <div class="single-post-area">
                        <!-- Post Thumbnail -->
                        <a href="#" class="post-thumbnail"><img src="{{artikel.thumbnail.url}}" alt=""></a>
                        <!-- Post Catagory -->
                        <a href="{% url 'blog:category' artikel.kategori.slug 1 %}"
                            class="btn post-catagory">{{artikel.kategori}}</a>
                        <!-- Post Conetent -->
                        <div class="post-content">
                            <div class="post-meta">
                                <a href="#">{{artikel.published}}</a>
                            </div>
                            <a href="{% url 'blog:detail' artikel.slug %}" class="post-title">{{artikel.judul}}</a>
                        </div>
                    </div>
                </div>
                {% else %}
                <div class="col-12 col-sm-6 col-lg-3">
                    <div class="shadow">
                        <div class="single-post-area">
                            <!-- Post Thumbnail -->
                            <a href="{% url 'blog:detail' artikel.slug %}" class="post-thumbnail"><img
                                    src="{{artikel.thumbnail.url}}" alt=""></a>
                            <!-- Post Catagory -->
                            <a href="{% url 'blog:category' artikel.kategori.slug 1 %}"
                                class="btn post-catagory">{{artikel.kategori}}</a>
                        </div>
                        <div class="post-content-wrap">
                            <!-- Post Conetent -->
                            <div class="container post-content-sm">
                                <div class="post-meta">
                                    {{artikel.isi|truncatewords:12|safe}}
                                    <br>
                                    <a href="#">{{artikel.published}}</a>
                                </div>
                                <a href="{% url 'blog:detail' artikel.slug %}" class="post-title">{{artikel.judul}}</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/blog/blog_update.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/blog.css' %}">
{% endblock style %}


{% block content %}
<div class="container text-center mt-5">
    <h1>Create Artikel</h1>
</div>
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {{form.media}}
        {{form.as_p}}
        <br>
        <button type="submit" class="btn btn-primary w-100">Tambah</button>
    </form>
</div>
{% endblock content %}